// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-wire/pkg/event"
	"go-wire/pkg/greeting"
	"go-wire/pkg/message"
)

// Injectors from wrie.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeEvent(phrase string) (event.Event, error) {
	messageMessage := message.NewMessage()
	greeter := greeting.NewGreeter(messageMessage)
	eventEvent := event.NewEvent(greeter)
	return eventEvent, nil
}
